products = [
    {
        '_id': 1,
        'name': 'Nars Soft Matte LongWear Foundation',
        'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
        'image': './makeup/face1.jpeg',
        'price': 32.00,
        'category': 'face',
        'rating': 4,
        'countInStock': 20,
        'numReviews': 10
    },
    {
        '_id': 2,
        'name': 'Sun Stalker face Bronzer',
        'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
        'image': './makeup/face2.jpeg',
        'price': 24.50,
        'category': 'face',
        'rating': 3,
        'countInStock': 20,
        'numReviews': 10
    },
    {
        '_id': 3,
        'name': 'Soft Matte face Powder',
        'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
        'image': './makeup/face3.jpeg',
        'price': 16.50,
        'category': 'face',
        'rating': 4,
        'countInStock': 20,
        'numReviews': 10
    },
    {
        '_id': 4,
        'name': 'Freestyle Cream Bronzer',
        'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
        'image': './makeup/cheek1.jpeg',
        'price': 24.50,
        'category': 'cheeks',
        'rating': 4,
        'countInStock': 7,
        'numReviews': 10
    },
    {'_id': 5,
     'name': 'Cheeks out cream blush',
     'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
     'image': './makeup/cheek2.jpeg',
     'price': 24.50,
     'category': 'cheeks',
     'rating': 5,
     'countInStock': 6,
     'numReviews': 10,
     },
    {
        '_id': 6,
        'name': 'Sun Stalked Instant Warmth Bronzer',
        'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
        'image': './makeup/cheek3.jpeg',
        'price': 16.50,
        'category': 'cheeks',
        'rating': 2,
        'countInStock': 12,
        'numReviews': 10,
    },
    {
        '_id': 7,
        'name': 'LongWear Pencil lip Liner',
        'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
        'image': './makeup/lips1.jpeg',
        'price': 9.50,
        'category': 'lips',
        'rating': 5,
        'countInStock': 5,
        'numReviews': 10

    },

    {'_id': 8,
     'name': 'Mademoiselle plush cream',
     'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
     'image': './makeup/lips2.jpeg',
     'price': 16.50,
     'category': 'lips',
     'rating': 2,
     'countInStock': 15,
     'numReviews': 10
     },
    {'_id': 9,
     'name': 'Gloss Bomb Heat lip Luminizer',
     'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
     'image': './makeup/lips3.jpeg',
     'price': 16.50,
     'category': 'lips',
     'rating': 3,
     'countInStock': 20,
     'numReviews': 10
     },
    {'_id': 10,
     'name': 'Precision makeup sponge',
     'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
     'image': './makeup/brush1.jpeg',
     'price': 9.50,
     'category': 'brushes',
     'rating': 3,
     'countInStock': 20,
     'numReviews': 10
     },
    {
        '_id': 11,
        'name': 'the 10 set full brush',
        'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
        'image': './makeup/brush2.jpeg',
        'price': 9.50,
        'category': 'brushes',
        'rating': 5,
        'countInStock': 20,
        'numReviews': 10
    },
    {
        '_id': 12,
        'name': 'Precision concealer brush',
        'description': 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus vitae hic, cupiditate quos alias distinctio officiis quidem possimus. Veritatis sequi, illum sint expedita molestiae aliquid vel dolorum error in odio.',
        'image': './makeup/brush3.jpeg',
        'price': 9.50,
        'category': 'brushes',
        'rating': 3,
        'countInStock': 20,
        'numReviews': 10
    }

]
